apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: springboot-example
    image: gazgeek/springboot-helloworld:latest
    ports:
    - containerPort: 8080
  - name: nodejs-example
    image: bitnami/node-example:0.0.1
    ports:
    - containerPort: 3000
