apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-resource-limit
spec:
  containers:
  - name: springboot-example
    image: gazgeek/springboot-helloworld:latest
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: nodejs-example
    image: bitnami/node-example:0.0.1
    ports:
    - containerPort: 3000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"