---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap-1
data:
  FIRST_NAME: "Jackson"
  LAST_ANME: "GOT7"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap-2
data:
  aws_account: "789548395438"
  aws_rgoin: ap-southeast-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
  labels:
    app: tester
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
      - name: tester
        image: selfieblue/connection-tester:centos8
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        # Define the environment variable
        - name: FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: sample-configmap-1
              key: FIRST_NAME
        - name: LAST_ANME
          valueFrom:
            configMapKeyRef:
              name: sample-configmap-1
              key: LAST_ANME
        envFrom:
        - configMapRef:
            name: sample-configmap-2